language: python

matrix:
  include:
    - { python: 3.5, env: TOXENV=py35-dj22 }
    - { python: 3.5, env: TOXENV=py35-dj22-grp }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj22 }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj22-grp }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj30 }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj30-grp }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj31 }
    - { python: 3.7, dist: xenial, env: TOXENV=py37-dj31 }
    - { python: 3.8, dist: xenial, env: TOXENV=py38-dj31 }

cache:
  pip: true
  directories:
    - node_modules
    - bin

addons:
  chrome: stable

env:
  global:
    - PATH=$HOME/bin:$PATH
    - PIXELMATCH_BIN=$TRAVIS_BUILD_DIR/node_modules/.bin/pixelmatch
    - DATABASE_URL=sqlite:////tmp/test.db

before_script:
  - mkdir -p ~/bin
  - |
    if [ ! -e ~/bin/chromedriver ]; then
      export CHROMEDRIVER_VERSION=$(curl -q http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P ~/
      unzip ~/chromedriver_linux64.zip -d ~/bin
      rm ~/chromedriver_linux64.zip
      chmod +x ~/bin/chromedriver
    fi

before_install:
  - nvm install 11
  - nvm use 11
  - travis_retry npm install
  - travis_retry npm install codecov pixelmatch
  - NODE_ENV=test npm run build

install:
  - pip install tox coverage codecov

script:
  - |
    travis_retry travis_retry tox -- \
      --selenosis-driver=chrome-headless -v --exitfirst
  - npm run report
  - npm run codecov
  - coverage xml
  - codecov -F python

sudo: false
